name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      # ✅ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ✅ Deploy to S3
      - name: Deploy static app to AWS S3
        run: |
          aws s3 sync . s3://awsmz-portfolio-web --delete
